version: "3.9"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file :
      - ./.env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - web
    depends_on:
      - wordpress
    restart : always

  wordpress:
    build : ./requirements/wordpress
    container_name : wordpress
    env_file :
      - ./.env
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - web

  mariadb:
    build : ./requirements/mariadb
    container_name : mariadb
    env_file :
      - ./.env
    expose: 
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - web

networks:
  web:
    name: inception

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/mafaisal/data/mariadb_data'
    

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: "/home/${USER}/data/wordpress"
