version: "3.9"

services:
  # nginx:
  #   build: ./requirements/nginx
  #   container_name: nginx
  #   env_file: ./.env
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - wordpress:/var/www/html/wordpress # This lets NGINX serve static WP files.
  #   networks:
  #     - web
  #   depends on:
  #     - wordpress
  #   restart : always # seems like not a good practice maybe we should do a health-check or something?

  # worpress:
  #   build : ./requirements/wordpress
  #   container_name : wordpress
  #   env_file : ./.env
  #   expose:
  #     - "9000" # Exposes PHP-FPM service (e.g., WordPress runs at port 9000 internally).
  #   volumes:
  #     - wordpress:/var/www/html/wordpress # The WordPress container generates dynamic content stored here
  #   networks:
  #     - web

  mariadb:
    build : ./requirements/mariadb
    container_name : mariadb
    env_file: ./.env
    enviroment:
      - MARIADB_ROOT_PASSWORD = ${MARIADB_ROOT_PASSWORD} # a psdd
      - DB_HOST = ${DB_HOST}
      - DB_CONF = ${DB_CONF}
    expose: 
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - web

networks:
  web:
    name: inception # lets try to run the compose without the name and check the name it will give

volumes:
  # wordpress:
  #   name: wordpress
  #   driver: local
  #   driver_opt:
  #     type: 'none'
  #     o: bind
  #     device: "/home/${USER}/data/wordpress"

  
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opt:
      type: 'none'
      o: bind
      device: "/home/data/mariadb_data"
